export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

// EDIT COMMENT MODE
export const EDIT_COMMENT_MODE = 'EDIT_COMMENT_MODE';
export const EDIT_COMMENT_MODE_SUCCESS = 'EDIT_COMMENT_MODE_SUCCESS';
export const EDIT_COMMENT_MODE_ERROR = 'EDIT_COMMENT_MODE_ERROR';

// EDIT COMMENT
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_ERROR = 'EDIT_COMMENT_ERROR';
