export const ADD_ANSWER_MODE = 'ADD_ANSWER_MODE';

export const TOGGLE_COMMENTS = 'TOGGLE_COMMENTS';

// ADD COMMENT
export const ADD_COMMENT = 'ADD_COMMENT';

// DELETE COMMENT
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

// EDIT COMMENT MODE
export const EDIT_COMMENT_MODE = 'EDIT_COMMENT_MODE';
export const EDIT_COMMENT_MODE_SUCCESS = 'EDIT_COMMENT_MODE_SUCCESS';
export const EDIT_COMMENT_MODE_ERROR = 'EDIT_COMMENT_MODE_ERROR';

// EDIT COMMENT
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_ERROR = 'EDIT_COMMENT_ERROR';

// FETCH COMMENT
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_ERROR = 'FETCH_COMMENT_ERROR';
export const FETCH_COMMENT_PENDING = 'FETCH_COMMENT_PENDING';
